/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ClubNidOrRouteImport } from './routes/club-nid-or'
import { Route as GuidesHyeresRouteImport } from './routes/guides-hyeres'
import { Route as MerciClubNidOrRouteImport } from './routes/merci-club-nid-or'
import { Route as MerciOffreDirecteRouteImport } from './routes/merci-offre-directe'
import { Route as OffresDirectesRouteImport } from './routes/offres-directes'
import { Route as ReserverEnDirectRouteImport } from './routes/reserver-en-direct'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ApiAppLogRouteImport } from './routes/api/app-log'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminGalleryUploadRouteImport } from './routes/api/admin/gallery/upload'
import { Route as ApiPublicGalleryNameRouteImport } from './routes/api/public/gallery/$name'
import { Route as ApiPublicHooksAgendaSyncRouteImport } from './routes/api/public/hooks/agenda-sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubNidOrRoute = ClubNidOrRouteImport.update({
  id: '/club-nid-or',
  path: '/club-nid-or',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesHyeresRoute = GuidesHyeresRouteImport.update({
  id: '/guides-hyeres',
  path: '/guides-hyeres',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciClubNidOrRoute = MerciClubNidOrRouteImport.update({
  id: '/merci-club-nid-or',
  path: '/merci-club-nid-or',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciOffreDirecteRoute = MerciOffreDirecteRouteImport.update({
  id: '/merci-offre-directe',
  path: '/merci-offre-directe',
  getParentRoute: () => rootRouteImport,
} as any)
const OffresDirectesRoute = OffresDirectesRouteImport.update({
  id: '/offres-directes',
  path: '/offres-directes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserverEnDirectRoute = ReserverEnDirectRouteImport.update({
  id: '/reserver-en-direct',
  path: '/reserver-en-direct',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppLogRoute = ApiAppLogRouteImport.update({
  id: '/api/app-log',
  path: '/api/app-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGalleryUploadRoute = ApiAdminGalleryUploadRouteImport.update({
  id: '/api/admin/gallery/upload',
  path: '/api/admin/gallery/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGalleryNameRoute = ApiPublicGalleryNameRouteImport.update({
  id: '/api/public/gallery/$name',
  path: '/api/public/gallery/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAgendaSyncRoute =
  ApiPublicHooksAgendaSyncRouteImport.update({
    id: '/api/public/hooks/agenda-sync',
    path: '/api/public/hooks/agenda-sync',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/club-nid-or': typeof ClubNidOrRoute
  '/guides-hyeres': typeof GuidesHyeresRoute
  '/merci-club-nid-or': typeof MerciClubNidOrRoute
  '/merci-offre-directe': typeof MerciOffreDirecteRoute
  '/offres-directes': typeof OffresDirectesRoute
  '/reserver-en-direct': typeof ReserverEnDirectRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/app-log': typeof ApiAppLogRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/gallery/upload': typeof ApiAdminGalleryUploadRoute
  '/api/public/gallery/$name': typeof ApiPublicGalleryNameRoute
  '/api/public/hooks/agenda-sync': typeof ApiPublicHooksAgendaSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/club-nid-or': typeof ClubNidOrRoute
  '/guides-hyeres': typeof GuidesHyeresRoute
  '/merci-club-nid-or': typeof MerciClubNidOrRoute
  '/merci-offre-directe': typeof MerciOffreDirecteRoute
  '/offres-directes': typeof OffresDirectesRoute
  '/reserver-en-direct': typeof ReserverEnDirectRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/app-log': typeof ApiAppLogRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/gallery/upload': typeof ApiAdminGalleryUploadRoute
  '/api/public/gallery/$name': typeof ApiPublicGalleryNameRoute
  '/api/public/hooks/agenda-sync': typeof ApiPublicHooksAgendaSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/club-nid-or': typeof ClubNidOrRoute
  '/guides-hyeres': typeof GuidesHyeresRoute
  '/merci-club-nid-or': typeof MerciClubNidOrRoute
  '/merci-offre-directe': typeof MerciOffreDirecteRoute
  '/offres-directes': typeof OffresDirectesRoute
  '/reserver-en-direct': typeof ReserverEnDirectRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/app-log': typeof ApiAppLogRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/gallery/upload': typeof ApiAdminGalleryUploadRoute
  '/api/public/gallery/$name': typeof ApiPublicGalleryNameRoute
  '/api/public/hooks/agenda-sync': typeof ApiPublicHooksAgendaSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/club-nid-or'
    | '/guides-hyeres'
    | '/merci-club-nid-or'
    | '/merci-offre-directe'
    | '/offres-directes'
    | '/reserver-en-direct'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/app-log'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/gallery/upload'
    | '/api/public/gallery/$name'
    | '/api/public/hooks/agenda-sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/club-nid-or'
    | '/guides-hyeres'
    | '/merci-club-nid-or'
    | '/merci-offre-directe'
    | '/offres-directes'
    | '/reserver-en-direct'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/app-log'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/gallery/upload'
    | '/api/public/gallery/$name'
    | '/api/public/hooks/agenda-sync'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/club-nid-or'
    | '/guides-hyeres'
    | '/merci-club-nid-or'
    | '/merci-offre-directe'
    | '/offres-directes'
    | '/reserver-en-direct'
    | '/rss.xml'
    | '/sitemap.xml'
    | '/api/app-log'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/gallery/upload'
    | '/api/public/gallery/$name'
    | '/api/public/hooks/agenda-sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRoute
  ClubNidOrRoute: typeof ClubNidOrRoute
  GuidesHyeresRoute: typeof GuidesHyeresRoute
  MerciClubNidOrRoute: typeof MerciClubNidOrRoute
  MerciOffreDirecteRoute: typeof MerciOffreDirecteRoute
  OffresDirectesRoute: typeof OffresDirectesRoute
  ReserverEnDirectRoute: typeof ReserverEnDirectRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAppLogRoute: typeof ApiAppLogRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminGalleryUploadRoute: typeof ApiAdminGalleryUploadRoute
  ApiPublicGalleryNameRoute: typeof ApiPublicGalleryNameRoute
  ApiPublicHooksAgendaSyncRoute: typeof ApiPublicHooksAgendaSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club-nid-or': {
      id: '/club-nid-or'
      path: '/club-nid-or'
      fullPath: '/club-nid-or'
      preLoaderRoute: typeof ClubNidOrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides-hyeres': {
      id: '/guides-hyeres'
      path: '/guides-hyeres'
      fullPath: '/guides-hyeres'
      preLoaderRoute: typeof GuidesHyeresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci-club-nid-or': {
      id: '/merci-club-nid-or'
      path: '/merci-club-nid-or'
      fullPath: '/merci-club-nid-or'
      preLoaderRoute: typeof MerciClubNidOrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci-offre-directe': {
      id: '/merci-offre-directe'
      path: '/merci-offre-directe'
      fullPath: '/merci-offre-directe'
      preLoaderRoute: typeof MerciOffreDirecteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offres-directes': {
      id: '/offres-directes'
      path: '/offres-directes'
      fullPath: '/offres-directes'
      preLoaderRoute: typeof OffresDirectesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserver-en-direct': {
      id: '/reserver-en-direct'
      path: '/reserver-en-direct'
      fullPath: '/reserver-en-direct'
      preLoaderRoute: typeof ReserverEnDirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/app-log': {
      id: '/api/app-log'
      path: '/api/app-log'
      fullPath: '/api/app-log'
      preLoaderRoute: typeof ApiAppLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/gallery/upload': {
      id: '/api/admin/gallery/upload'
      path: '/api/admin/gallery/upload'
      fullPath: '/api/admin/gallery/upload'
      preLoaderRoute: typeof ApiAdminGalleryUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gallery/$name': {
      id: '/api/public/gallery/$name'
      path: '/api/public/gallery/$name'
      fullPath: '/api/public/gallery/$name'
      preLoaderRoute: typeof ApiPublicGalleryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agenda-sync': {
      id: '/api/public/hooks/agenda-sync'
      path: '/api/public/hooks/agenda-sync'
      fullPath: '/api/public/hooks/agenda-sync'
      preLoaderRoute: typeof ApiPublicHooksAgendaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  ClubNidOrRoute: ClubNidOrRoute,
  GuidesHyeresRoute: GuidesHyeresRoute,
  MerciClubNidOrRoute: MerciClubNidOrRoute,
  MerciOffreDirecteRoute: MerciOffreDirecteRoute,
  OffresDirectesRoute: OffresDirectesRoute,
  ReserverEnDirectRoute: ReserverEnDirectRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAppLogRoute: ApiAppLogRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminGalleryUploadRoute: ApiAdminGalleryUploadRoute,
  ApiPublicGalleryNameRoute: ApiPublicGalleryNameRoute,
  ApiPublicHooksAgendaSyncRoute: ApiPublicHooksAgendaSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
