/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAppLogRouteImport } from './routes/api/app-log'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'
import { Route as ApiPublicGalleryNameRouteImport } from './routes/api/public/gallery/$name'
import { Route as ApiAdminGalleryUploadRouteImport } from './routes/api/admin/gallery/upload'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppLogRoute = ApiAppLogRouteImport.update({
  id: '/api/app-log',
  path: '/api/app-log',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGalleryNameRoute = ApiPublicGalleryNameRouteImport.update({
  id: '/api/public/gallery/$name',
  path: '/api/public/gallery/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGalleryUploadRoute = ApiAdminGalleryUploadRouteImport.update({
  id: '/api/admin/gallery/upload',
  path: '/api/admin/gallery/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/app-log': typeof ApiAppLogRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/gallery/upload': typeof ApiAdminGalleryUploadRoute
  '/api/public/gallery/$name': typeof ApiPublicGalleryNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/app-log': typeof ApiAppLogRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/gallery/upload': typeof ApiAdminGalleryUploadRoute
  '/api/public/gallery/$name': typeof ApiPublicGalleryNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/app-log': typeof ApiAppLogRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
  '/api/admin/gallery/upload': typeof ApiAdminGalleryUploadRoute
  '/api/public/gallery/$name': typeof ApiPublicGalleryNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/admin'
    | '/sitemap.xml'
    | '/api/app-log'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/gallery/upload'
    | '/api/public/gallery/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/admin'
    | '/sitemap.xml'
    | '/api/app-log'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/gallery/upload'
    | '/api/public/gallery/$name'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/admin'
    | '/sitemap.xml'
    | '/api/app-log'
    | '/api/admin/login'
    | '/api/admin/logout'
    | '/api/admin/gallery/upload'
    | '/api/public/gallery/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AdminRoute: typeof AdminRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAppLogRoute: typeof ApiAppLogRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
  ApiAdminGalleryUploadRoute: typeof ApiAdminGalleryUploadRoute
  ApiPublicGalleryNameRoute: typeof ApiPublicGalleryNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/app-log': {
      id: '/api/app-log'
      path: '/api/app-log'
      fullPath: '/api/app-log'
      preLoaderRoute: typeof ApiAppLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gallery/$name': {
      id: '/api/public/gallery/$name'
      path: '/api/public/gallery/$name'
      fullPath: '/api/public/gallery/$name'
      preLoaderRoute: typeof ApiPublicGalleryNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/gallery/upload': {
      id: '/api/admin/gallery/upload'
      path: '/api/admin/gallery/upload'
      fullPath: '/api/admin/gallery/upload'
      preLoaderRoute: typeof ApiAdminGalleryUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AdminRoute: AdminRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAppLogRoute: ApiAppLogRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
  ApiAdminGalleryUploadRoute: ApiAdminGalleryUploadRoute,
  ApiPublicGalleryNameRoute: ApiPublicGalleryNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
