/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAdminLogoutRouteImport } from './routes/api/admin/logout'
import { Route as ApiAdminLoginRouteImport } from './routes/api/admin/login'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLogoutRoute = ApiAdminLogoutRouteImport.update({
  id: '/api/admin/logout',
  path: '/api/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminLoginRoute = ApiAdminLoginRouteImport.update({
  id: '/api/admin/login',
  path: '/api/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/admin/login': typeof ApiAdminLoginRoute
  '/api/admin/logout': typeof ApiAdminLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/api/admin/login'
    | '/api/admin/logout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/sitemap.xml' | '/api/admin/login' | '/api/admin/logout'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/sitemap.xml'
    | '/api/admin/login'
    | '/api/admin/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAdminLoginRoute: typeof ApiAdminLoginRoute
  ApiAdminLogoutRoute: typeof ApiAdminLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/logout': {
      id: '/api/admin/logout'
      path: '/api/admin/logout'
      fullPath: '/api/admin/logout'
      preLoaderRoute: typeof ApiAdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/login': {
      id: '/api/admin/login'
      path: '/api/admin/login'
      fullPath: '/api/admin/login'
      preLoaderRoute: typeof ApiAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAdminLoginRoute: ApiAdminLoginRoute,
  ApiAdminLogoutRoute: ApiAdminLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
